// ============================================
// ABC Express AIP — Ontology Object Types
// Domain entity definitions for the ontology
// ============================================

import type { ObjectTypeDefinition } from './types.js';

export const shipmentObjectType: ObjectTypeDefinition = {
  apiName: 'shipment',
  displayName: 'Shipment',
  pluralName: 'Shipments',
  description: 'A cargo shipment from origin to destination with tracking, pricing, and status lifecycle.',
  icon: 'package',
  dataSource: 'Shipment',
  primaryKeyProperty: 'id',
  titleProperty: 'connoteNumber',
  tags: ['operations', 'core'],
  readRoles: ['ADMIN', 'OPS_MANAGER', 'FINANCE_MANAGER', 'DISPATCHER', 'BRANCH_STAFF', 'VIEWER'],
  writeRoles: ['ADMIN', 'OPS_MANAGER', 'DISPATCHER', 'BRANCH_STAFF'],
  properties: [
    { key: 'id', label: 'ID', type: 'string', primaryKey: true, searchable: false, sortable: false, filterable: false },
    { key: 'connoteNumber', label: 'Connote Number', type: 'string', required: true, searchable: true, sortable: true, filterable: true, description: 'Unique consignment note number (ABC prefix)' },
    { key: 'serviceType', label: 'Service Type', type: 'enum', enumValues: ['REGULAR', 'EXPRESS', 'SAME_DAY', 'CARGO', 'PROJECT_CARGO', 'VEHICLE_TRANSPORT', 'HEAVY_EQUIPMENT', 'EXPORT', 'IMPORT'], required: true, searchable: false, sortable: true, filterable: true },
    { key: 'status', label: 'Status', type: 'enum', enumValues: ['PENDING', 'PICKED_UP', 'IN_TRANSIT', 'AT_HUB', 'OUT_FOR_DELIVERY', 'DELIVERED', 'RETURNED', 'CANCELLED', 'ON_HOLD'], required: true, sortable: true, filterable: true },
    { key: 'weightKg', label: 'Weight', type: 'number', unit: 'kg', sortable: true, filterable: true },
    { key: 'volumeM3', label: 'Volume', type: 'number', unit: 'm³', sortable: true },
    { key: 'packageCount', label: 'Package Count', type: 'number', sortable: true },
    { key: 'senderName', label: 'Sender Name', type: 'string', searchable: true },
    { key: 'senderPhone', label: 'Sender Phone', type: 'string' },
    { key: 'senderAddress', label: 'Sender Address', type: 'string' },
    { key: 'receiverName', label: 'Receiver Name', type: 'string', searchable: true },
    { key: 'receiverPhone', label: 'Receiver Phone', type: 'string' },
    { key: 'receiverAddress', label: 'Receiver Address', type: 'string' },
    { key: 'goodsDescription', label: 'Goods Description', type: 'string', searchable: true },
    { key: 'baseCharge', label: 'Base Charge', type: 'number', unit: 'IDR', sortable: true },
    { key: 'surcharges', label: 'Surcharges', type: 'number', unit: 'IDR' },
    { key: 'insuranceCharge', label: 'Insurance Charge', type: 'number', unit: 'IDR' },
    { key: 'totalChargeAmount', label: 'Total Charge', type: 'number', unit: 'IDR', sortable: true, filterable: true },
    { key: 'estimatedDeliveryDate', label: 'Estimated Delivery', type: 'date', sortable: true },
    { key: 'actualDeliveryDate', label: 'Actual Delivery', type: 'date', sortable: true },
    { key: 'specialInstructions', label: 'Special Instructions', type: 'string' },
    { key: 'createdAt', label: 'Created At', type: 'datetime', sortable: true },
    { key: 'updatedAt', label: 'Updated At', type: 'datetime', sortable: true },
  ],
};

export const branchObjectType: ObjectTypeDefinition = {
  apiName: 'branch',
  displayName: 'Branch',
  pluralName: 'Branches',
  description: 'An ABC Express operational branch or hub location.',
  icon: 'building',
  dataSource: 'Branch',
  primaryKeyProperty: 'id',
  titleProperty: 'name',
  tags: ['operations', 'core'],
  readRoles: ['ADMIN', 'OPS_MANAGER', 'FINANCE_MANAGER', 'DISPATCHER', 'BRANCH_STAFF', 'VIEWER'],
  writeRoles: ['ADMIN'],
  properties: [
    { key: 'id', label: 'ID', type: 'string', primaryKey: true },
    { key: 'code', label: 'Branch Code', type: 'string', required: true, searchable: true, sortable: true, filterable: true },
    { key: 'name', label: 'Branch Name', type: 'string', required: true, searchable: true, sortable: true },
    { key: 'type', label: 'Type', type: 'enum', enumValues: ['HUB', 'BRANCH', 'SUB_BRANCH', 'AGENT', 'PORT', 'AIRPORT'], filterable: true, sortable: true },
    { key: 'city', label: 'City', type: 'string', searchable: true, filterable: true, sortable: true },
    { key: 'province', label: 'Province', type: 'string', filterable: true, sortable: true },
    { key: 'region', label: 'Region', type: 'string', filterable: true, sortable: true },
    { key: 'address', label: 'Address', type: 'string' },
    { key: 'phone', label: 'Phone', type: 'string' },
    { key: 'latitude', label: 'Latitude', type: 'number' },
    { key: 'longitude', label: 'Longitude', type: 'number' },
    { key: 'isActive', label: 'Active', type: 'boolean', filterable: true },
    { key: 'createdAt', label: 'Created At', type: 'datetime', sortable: true },
  ],
};

export const clientObjectType: ObjectTypeDefinition = {
  apiName: 'client',
  displayName: 'Client',
  pluralName: 'Clients',
  description: 'A corporate or retail customer of ABC Express.',
  icon: 'users',
  dataSource: 'Client',
  primaryKeyProperty: 'id',
  titleProperty: 'name',
  tags: ['operations', 'finance'],
  readRoles: ['ADMIN', 'OPS_MANAGER', 'FINANCE_MANAGER', 'DISPATCHER'],
  writeRoles: ['ADMIN', 'OPS_MANAGER'],
  properties: [
    { key: 'id', label: 'ID', type: 'string', primaryKey: true },
    { key: 'code', label: 'Client Code', type: 'string', required: true, searchable: true, sortable: true },
    { key: 'name', label: 'Contact Name', type: 'string', required: true, searchable: true, sortable: true },
    { key: 'companyName', label: 'Company', type: 'string', searchable: true, sortable: true },
    { key: 'type', label: 'Type', type: 'enum', enumValues: ['CORPORATE', 'RETAIL', 'GOVERNMENT', 'INTERNAL'], filterable: true },
    { key: 'email', label: 'Email', type: 'string', searchable: true },
    { key: 'phone', label: 'Phone', type: 'string' },
    { key: 'address', label: 'Address', type: 'string' },
    { key: 'city', label: 'City', type: 'string', filterable: true },
    { key: 'province', label: 'Province', type: 'string', filterable: true },
    { key: 'npwp', label: 'NPWP', type: 'string', description: 'Tax ID number' },
    { key: 'creditLimit', label: 'Credit Limit', type: 'number', unit: 'IDR', sortable: true },
    { key: 'paymentTermDays', label: 'Payment Term', type: 'number', unit: 'days' },
    { key: 'isActive', label: 'Active', type: 'boolean', filterable: true },
    { key: 'createdAt', label: 'Created At', type: 'datetime', sortable: true },
  ],
};

export const vehicleObjectType: ObjectTypeDefinition = {
  apiName: 'vehicle',
  displayName: 'Vehicle',
  pluralName: 'Vehicles',
  description: 'A fleet vehicle (truck, ship, plane) used for shipment transport.',
  icon: 'truck',
  dataSource: 'Vehicle',
  primaryKeyProperty: 'id',
  titleProperty: 'plateNumber',
  tags: ['operations', 'fleet'],
  readRoles: ['ADMIN', 'OPS_MANAGER', 'DISPATCHER'],
  writeRoles: ['ADMIN', 'OPS_MANAGER'],
  properties: [
    { key: 'id', label: 'ID', type: 'string', primaryKey: true },
    { key: 'plateNumber', label: 'Plate Number', type: 'string', required: true, searchable: true, sortable: true },
    { key: 'type', label: 'Type', type: 'enum', enumValues: ['TRUCK_SMALL', 'TRUCK_MEDIUM', 'TRUCK_LARGE', 'TRUCK_TRAILER', 'VAN', 'PICKUP', 'SHIP', 'AIRPLANE'], filterable: true, sortable: true },
    { key: 'brand', label: 'Brand', type: 'string', filterable: true },
    { key: 'model', label: 'Model', type: 'string' },
    { key: 'year', label: 'Year', type: 'number', sortable: true },
    { key: 'maxWeightKg', label: 'Max Weight', type: 'number', unit: 'kg', sortable: true },
    { key: 'maxVolumeM3', label: 'Max Volume', type: 'number', unit: 'm³' },
    { key: 'status', label: 'Status', type: 'enum', enumValues: ['AVAILABLE', 'IN_TRANSIT', 'MAINTENANCE', 'RETIRED'], filterable: true, sortable: true },
    { key: 'currentBranchId', label: 'Current Branch', type: 'string', filterable: true },
    { key: 'driverName', label: 'Driver Name', type: 'string', searchable: true },
    { key: 'driverPhone', label: 'Driver Phone', type: 'string' },
    { key: 'lastMaintenanceDate', label: 'Last Maintenance', type: 'date', sortable: true },
    { key: 'createdAt', label: 'Created At', type: 'datetime', sortable: true },
  ],
};

export const invoiceObjectType: ObjectTypeDefinition = {
  apiName: 'invoice',
  displayName: 'Invoice',
  pluralName: 'Invoices',
  description: 'A financial invoice for shipment services rendered.',
  icon: 'file-text',
  dataSource: 'Invoice',
  primaryKeyProperty: 'id',
  titleProperty: 'invoiceNumber',
  tags: ['finance'],
  readRoles: ['ADMIN', 'FINANCE_MANAGER', 'OPS_MANAGER'],
  writeRoles: ['ADMIN', 'FINANCE_MANAGER'],
  properties: [
    { key: 'id', label: 'ID', type: 'string', primaryKey: true },
    { key: 'invoiceNumber', label: 'Invoice Number', type: 'string', required: true, searchable: true, sortable: true },
    { key: 'status', label: 'Status', type: 'enum', enumValues: ['DRAFT', 'SENT', 'PARTIAL', 'PAID', 'OVERDUE', 'CANCELLED', 'VOID'], filterable: true, sortable: true },
    { key: 'totalAmount', label: 'Total Amount', type: 'number', unit: 'IDR', sortable: true },
    { key: 'taxAmount', label: 'Tax Amount', type: 'number', unit: 'IDR' },
    { key: 'paidAmount', label: 'Paid Amount', type: 'number', unit: 'IDR', sortable: true },
    { key: 'issuedDate', label: 'Issued Date', type: 'date', sortable: true, filterable: true },
    { key: 'dueDate', label: 'Due Date', type: 'date', sortable: true, filterable: true },
    { key: 'paidDate', label: 'Paid Date', type: 'date', sortable: true },
    { key: 'notes', label: 'Notes', type: 'string' },
    { key: 'createdAt', label: 'Created At', type: 'datetime', sortable: true },
  ],
};

export const costEntryObjectType: ObjectTypeDefinition = {
  apiName: 'costEntry',
  displayName: 'Cost Entry',
  pluralName: 'Cost Entries',
  description: 'An operational cost incurred for a shipment (transport, handling, customs, etc.).',
  icon: 'credit-card',
  dataSource: 'CostEntry',
  primaryKeyProperty: 'id',
  titleProperty: 'description',
  tags: ['finance', 'operations'],
  readRoles: ['ADMIN', 'FINANCE_MANAGER', 'OPS_MANAGER'],
  writeRoles: ['ADMIN', 'FINANCE_MANAGER', 'OPS_MANAGER'],
  properties: [
    { key: 'id', label: 'ID', type: 'string', primaryKey: true },
    { key: 'category', label: 'Category', type: 'enum', enumValues: ['TRANSPORT', 'HANDLING', 'CUSTOMS', 'INSURANCE', 'STORAGE', 'FUEL', 'TOLL', 'LABOR', 'PACKAGING', 'OTHER'], filterable: true, sortable: true },
    { key: 'description', label: 'Description', type: 'string', searchable: true },
    { key: 'amount', label: 'Amount', type: 'number', unit: 'IDR', sortable: true },
    { key: 'vendorName', label: 'Vendor', type: 'string', searchable: true, filterable: true },
    { key: 'receiptNumber', label: 'Receipt Number', type: 'string', searchable: true },
    { key: 'incurredDate', label: 'Incurred Date', type: 'date', sortable: true, filterable: true },
    { key: 'createdAt', label: 'Created At', type: 'datetime', sortable: true },
  ],
};

export const routeObjectType: ObjectTypeDefinition = {
  apiName: 'route',
  displayName: 'Route',
  pluralName: 'Routes',
  description: 'A defined transport route between two branches with mode, distance, and cost parameters.',
  icon: 'map-pin',
  dataSource: 'Route',
  primaryKeyProperty: 'id',
  titleProperty: 'code',
  tags: ['operations', 'network'],
  readRoles: ['ADMIN', 'OPS_MANAGER', 'DISPATCHER', 'BRANCH_STAFF'],
  writeRoles: ['ADMIN', 'OPS_MANAGER'],
  properties: [
    { key: 'id', label: 'ID', type: 'string', primaryKey: true },
    { key: 'code', label: 'Route Code', type: 'string', required: true, searchable: true, sortable: true },
    { key: 'mode', label: 'Transport Mode', type: 'enum', enumValues: ['ROAD', 'SEA', 'AIR', 'RAIL', 'MULTIMODAL'], filterable: true, sortable: true },
    { key: 'distanceKm', label: 'Distance', type: 'number', unit: 'km', sortable: true },
    { key: 'estimatedHours', label: 'Estimated Hours', type: 'number', unit: 'hours', sortable: true },
    { key: 'baseCostPerKg', label: 'Cost per Kg', type: 'number', unit: 'IDR/kg', sortable: true },
    { key: 'isActive', label: 'Active', type: 'boolean', filterable: true },
    { key: 'createdAt', label: 'Created At', type: 'datetime', sortable: true },
  ],
};

export const proposalObjectType: ObjectTypeDefinition = {
  apiName: 'proposal',
  displayName: 'Proposal',
  pluralName: 'Proposals',
  description:
    'A first-class change proposal (draft or submitted). Merging into a Decision creates an AI_RECOMMENDED decision and links 1:1 via Decision.proposalId.',
  icon: 'file-diff',
  dataSource: 'Proposal',
  primaryKeyProperty: 'id',
  titleProperty: 'type',
  tags: ['ai', 'governance'],
  readRoles: ['ADMIN', 'OPS_MANAGER', 'DISPATCHER'],
  writeRoles: ['ADMIN', 'OPS_MANAGER'],
  properties: [
    { key: 'id', label: 'ID', type: 'string', primaryKey: true },
    { key: 'type', label: 'Decision Type (on merge)', type: 'enum', enumValues: ['SHIPMENT_ROUTING', 'PRICING', 'DISPATCH', 'ESCALATION', 'COST_OPTIMIZATION', 'CAPACITY_PLANNING'], filterable: true, sortable: true },
    { key: 'status', label: 'Status', type: 'enum', enumValues: ['DRAFT', 'SUBMITTED', 'MERGED', 'REJECTED', 'CANCELLED'], filterable: true, sortable: true },
    { key: 'entityType', label: 'Entity Type', type: 'string', filterable: true },
    { key: 'entityId', label: 'Entity ID', type: 'string' },
    { key: 'proposedPayload', label: 'Proposed payload', type: 'json' },
    { key: 'rationale', label: 'Rationale', type: 'string' },
    { key: 'confidence', label: 'Confidence', type: 'number', sortable: true, filterable: true },
    { key: 'source', label: 'Source', type: 'string' },
    { key: 'mergedAt', label: 'Merged at', type: 'datetime', sortable: true },
    { key: 'rejectReason', label: 'Reject reason', type: 'string' },
    { key: 'createdAt', label: 'Created At', type: 'datetime', sortable: true },
  ],
};

export const decisionObjectType: ObjectTypeDefinition = {
  apiName: 'decision',
  displayName: 'AI Decision',
  pluralName: 'AI Decisions',
  description: 'An AI recommendation with human-in-the-loop approval workflow. May originate from a merged Proposal (proposalId).',
  icon: 'brain',
  dataSource: 'Decision',
  primaryKeyProperty: 'id',
  titleProperty: 'type',
  tags: ['ai', 'governance'],
  readRoles: ['ADMIN', 'OPS_MANAGER', 'DISPATCHER'],
  writeRoles: ['ADMIN', 'OPS_MANAGER'],
  properties: [
    { key: 'id', label: 'ID', type: 'string', primaryKey: true },
    { key: 'proposalId', label: 'Source proposal', type: 'string', description: 'Set when this decision was created from a merged proposal' },
    { key: 'type', label: 'Decision Type', type: 'enum', enumValues: ['SHIPMENT_ROUTING', 'PRICING', 'DISPATCH', 'ESCALATION', 'COST_OPTIMIZATION', 'CAPACITY_PLANNING'], filterable: true, sortable: true },
    { key: 'status', label: 'Status', type: 'enum', enumValues: ['PENDING', 'AI_RECOMMENDED', 'HUMAN_APPROVED', 'HUMAN_OVERRIDDEN', 'EXECUTED', 'REJECTED'], filterable: true, sortable: true },
    { key: 'entityType', label: 'Entity Type', type: 'string', filterable: true },
    { key: 'entityId', label: 'Entity ID', type: 'string' },
    { key: 'aiRecommendation', label: 'AI Recommendation', type: 'json' },
    { key: 'aiReasoning', label: 'AI Reasoning', type: 'string' },
    { key: 'aiConfidence', label: 'AI Confidence', type: 'number', sortable: true, filterable: true },
    { key: 'humanDecision', label: 'Human decision', type: 'json' },
    { key: 'humanReasoning', label: 'Human reasoning', type: 'string' },
    { key: 'decidedAt', label: 'Decided At', type: 'datetime', sortable: true },
    { key: 'createdAt', label: 'Created At', type: 'datetime', sortable: true },
  ],
};

export const userObjectType: ObjectTypeDefinition = {
  apiName: 'user',
  displayName: 'User',
  pluralName: 'Users',
  description: 'A system user with role-based access control.',
  icon: 'user',
  dataSource: 'User',
  primaryKeyProperty: 'id',
  titleProperty: 'name',
  tags: ['admin'],
  readRoles: ['ADMIN'],
  writeRoles: ['ADMIN'],
  properties: [
    { key: 'id', label: 'ID', type: 'string', primaryKey: true },
    { key: 'email', label: 'Email', type: 'string', required: true, searchable: true, sortable: true },
    { key: 'name', label: 'Name', type: 'string', required: true, searchable: true, sortable: true },
    { key: 'role', label: 'Role', type: 'enum', enumValues: ['ADMIN', 'OPS_MANAGER', 'FINANCE_MANAGER', 'DISPATCHER', 'BRANCH_STAFF', 'VIEWER'], filterable: true, sortable: true },
    { key: 'isActive', label: 'Active', type: 'boolean', filterable: true },
    { key: 'createdAt', label: 'Created At', type: 'datetime', sortable: true },
  ],
};

/** All registered object types */
export const ALL_OBJECT_TYPES: ObjectTypeDefinition[] = [
  shipmentObjectType,
  branchObjectType,
  clientObjectType,
  vehicleObjectType,
  invoiceObjectType,
  costEntryObjectType,
  routeObjectType,
  proposalObjectType,
  decisionObjectType,
  userObjectType,
];
